version: '3.8'

services:
  fastapi_app:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile # Specify the Dockerfile name
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    env_file:
      - .env # Load environment variables from .env file
    volumes:
      - ./app:/app/app # Mount the app directory for hot-reloading (optional)
    depends_on:
      - celery_worker
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/app/app # Mount the app directory (if worker needs to see code changes without rebuild)
    restart: unless-stopped
    command: celery -A app.worker.celery_app worker -l INFO --concurrency=1 # Adjust concurrency as needed 