version: '3.8'

services:
  fastapi_app:
    build:
      context: .  # Use repo root where Dockerfile lives
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Optional: expose for debugging; not needed in prod
    env_file:
      - .env
    volumes:
      - ./pyautocausal_api/app:/app/app  # Optional hot-reload
    depends_on: []  # Caddy will proxy; no Celery worker
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  # Reverse proxy with automatic HTTPS (Caddy)
  caddy:
    image: caddy:latest
    container_name: caddy
    depends_on:
      - fastapi_app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./pyautocausal_api/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: 